version: "3.9"
services:
  #* Service name
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      #* Bind-mounts configuration
      - ./client:/client
      #* Ignoring any changes made in "node_modules" folder
      - /client/node_modules
    ports:
      #* External port:Internal port
      - 3000:3000
    environment:
      #* Enabling hot reload
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      #* Starts up the node service before starting up the react service
      - server
  server:
    #* Creating a custom image
    build:
      #* Location to the Dockerfile
      context: ./server
      #* Name of the Dockerfile
      dockerfile: ./Dockerfile
    ports:
      #* External port: Internal port
      - "3001:3001"
    volumes:
      #* ADD THE CONFIGURATION FROM THIS POINT to create a volume named serverVolume
      - serverVolume:/server
      #* ADD THE CONFIGURATION FROM THIS POINT to sync the working directory
      - .:/server:ro #* read-only option
      - /server/node_modules
#* Making the node service volume accessible to other services.
volumes:
  #* Declaring the node service volume.
  serverVolume: